apiVersion: v1
entries:
  open-webconcept:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2021-05-26T15:44:23.4674001+02:00"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
    digest: a62d0858dd17b6733e018a093e85cd28556fa11de05e91394b7d14b7ca173144
    home: https://openwebconcept.nl/
    icon: https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo-dark.png
    name: open-webconcept
    urls:
    - open-webconcept-0.1.0.tgz
    version: 0.1.0
generated: "2021-05-26T15:44:23.4654068+02:00"
